package com.example.gestiondepartement.rest;

import lombok.Getter;
import lombok.Setter;

import java.util.Date;
import java.util.List;

@Getter
@Setter
public class ArticleDTO {

    private Long id;
    private String titre;
    private String description;
    private Date publicationDate;

    private Long publisher; // Field name updated for clarity

    private Boolean isActive;
    private String doi;  // DOI field added

    private String pdfUrl; // URL to access the PDF, if applicable

    // Assuming you want to only send basic member information like IDs or names
    private List<Long> authorIds;

    // Constructors
    public ArticleDTO() {}

    // Getters and setters are auto-generated by Lombok, hence not explicitly included here
}
